# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Main
      run: |
        curl https://patoflamejantetv.github.io/res/test.txt | python3 raincmdbow.py -p -i 0.01
        curl https://patoflamejantetv.github.io/res/test.txt | python3 raincmdbow.py -p -i 0.001
